/**
 * Extensions for Telegram Bot API updates related to topics in private chats
 * Based on Telegram Bot API 8.0+ updates
 */

/**
 * Extended User type with topic support in private chats
 * @see https://core.telegram.org/bots/api#user
 */
export interface UserWithTopics {
  id: number;
  is_bot: boolean;
  first_name: string;
  last_name?: string;
  username?: string;
  language_code?: string;
  is_premium?: boolean;
  added_to_attachment_menu?: boolean;
  can_join_groups?: boolean;
  can_read_all_group_messages?: boolean;
  supports_inline_queries?: boolean;
  can_connect_to_business?: boolean;
  has_main_web_app?: boolean;
  /** NEW: Whether forum topic mode is enabled for the bot in private chats */
  has_topics_enabled?: boolean;
}

/**
 * Extended Message type with topic support in private chats
 * @see https://core.telegram.org/bots/api#message
 */
export interface MessageWithTopics {
  message_id: number;
  message_thread_id?: number;
  /** NEW: True, if the message is sent to a forum topic */
  is_topic_message?: boolean;
  date: number;
  chat: any; // Full chat object
  from?: any; // User object
  sender_chat?: any; // Chat object for sent from user's business account
  sender_boost_count?: number;
  sender_business_bot_id?: number;
  // ... other message fields
}

/**
 * Forum topic info with implicit name support
 * @see https://core.telegram.org/bots/api#forumtopic
 */
export interface ForumTopicWithImplicitName {
  message_thread_id: number;
  name: string;
  icon_color: number;
  icon_custom_emoji_id?: string;
  /** NEW: True if the topic name was automatically generated by forum creation options */
  is_name_implicit?: boolean;
}

/**
 * Forum topic created info with implicit name support
 * @see https://core.telegram.org/bots/api#forumtopiccreated
 */
export interface ForumTopicCreatedWithImplicitName {
  name: string;
  icon_color: number;
  icon_custom_emoji_id?: string;
  /** NEW: True if the topic name was automatically generated by forum creation options */
  is_name_implicit?: boolean;
}

/**
 * Parameters for sending messages with topic support
 */
export interface SendMessageWithTopicParams {
  chat_id: number | string;
  text: string;
  /** Topic thread ID for private chats with topics enabled */
  message_thread_id?: number;
  parse_mode?: 'HTML' | 'Markdown' | 'MarkdownV2';
  entities?: any[];
  link_preview_options?: any;
  reply_markup?: any;
  reply_to_message_id?: number;
  allow_user_without_premium?: boolean;
  disable_notification?: boolean;
  protect_content?: boolean;
  allow_sending_without_reply?: boolean;
  reply_to_story_id?: number;
  business_connection_id?: string;
}

/**
 * Parameters for sending chat action with topic support
 */
export interface SendChatActionWithTopicParams {
  chat_id: number | string;
  action:
    | 'typing'
    | 'upload_photo'
    | 'record_video'
    | 'upload_video'
    | 'record_voice'
    | 'upload_voice'
    | 'upload_document'
    | 'choose_sticker'
    | 'find_location'
    | 'record_video_note'
    | 'upload_video_note';
  /** Topic thread ID for private chats with topics enabled */
  message_thread_id?: number;
  business_connection_id?: string;
}

/**
 * Parameters for sendMessageDraft API
 * Allows streaming partial messages to a user while being generated
 */
export interface SendMessageDraftParams {
  chat_id: number | string;
  text: string;
  /** Topic thread ID for private chats with topics enabled */
  message_thread_id?: number;
  parse_mode?: 'HTML' | 'Markdown' | 'MarkdownV2';
  entities?: any[];
  link_preview_options?: any;
  business_connection_id?: string;
}

/**
 * Parameters for editing messages with topic support
 */
export interface EditMessageTextWithTopicParams {
  chat_id?: number | string;
  message_id?: number;
  inline_message_id?: string;
  text: string;
  parse_mode?: 'HTML' | 'Markdown' | 'MarkdownV2';
  entities?: any[];
  link_preview_options?: any;
  reply_markup?: any;
  business_connection_id?: string;
}

/**
 * Context extension for tracking user topic settings
 */
export interface UserTopicContext {
  userId: string;
  hasTopicsEnabled?: boolean;
  currentMessageThreadId?: number;
  lastTopicMessageId?: number;
}

/**
 * Configuration for topic-aware message sending
 */
export interface TopicAwareSendConfig {
  /** Whether to use sendMessageDraft for streaming messages */
  useStreamingDraft: boolean;
  /** Default message_thread_id if user has topics enabled */
  messageThreadId?: number;
  /** Update interval in milliseconds for draft messages */
  updateInterval?: number;
  /** Maximum length before splitting draft content */
  maxDraftLength?: number;
}
